"""INDEX.md updater for workstreams."""

from pathlib import Path


class IndexUpdater:
    """Updates docs/workstreams/INDEX.md when workstreams move."""

    INDEX_PATH = "docs/workstreams/INDEX.md"

    def update(self, ws_id: str, old_status: str, new_status: str) -> None:
        """Update INDEX.md after workstream move.

        Args:
            ws_id: Workstream ID
            old_status: Previous status
            new_status: New status
        """
        index_path = Path(self.INDEX_PATH)

        if not index_path.exists():
            return

        content = index_path.read_text()

        # Simple find and replace - look for ws_id in old status section
        # This is a simplified implementation
        old_line = f"- [{ws_id}]"
        new_line = f"- [{ws_id}]"

        # Update the status section reference
        content = content.replace(f"{old_status}/{ws_id}", f"{new_status}/{ws_id}")

        index_path.write_text(content)

    def add_entry(self, ws_id: str, title: str, status: str, feature: str) -> None:
        """Add workstream entry to INDEX.md.

        Args:
            ws_id: Workstream ID
            title: Workstream title
            status: Current status
            feature: Feature ID
        """
        index_path = Path(self.INDEX_PATH)
        index_path.parent.mkdir(parents=True, exist_ok=True)

        if not index_path.exists():
            # Create new index
            content = self._create_index_header()
        else:
            content = index_path.read_text()

        # Add entry to appropriate section
        entry = f"- [{ws_id}](./{status.replace('-', '_')}/{ws_id}..md): {title} ({feature})\n"

        # Find the status section or create it
        status_header = f"### {status.replace('-', ' ').title()}\n"

        if status_header in content:
            # Append to existing section
            content = content.replace(
                status_header,
                status_header + entry
            )
        else:
            # Add new section
            content += f"\n{status_header}\n{entry}"

        index_path.write_text(content)

    def _create_index_header(self) -> str:
        """Create default INDEX.md header.

        Returns:
            Default index content
        """
        return """# Workstreams Index

This file is auto-generated by the SDP workspace management tools.

## Status Sections

"""
