"""File creation utilities for SDP init wizard."""

from datetime import datetime
from pathlib import Path

from sdp.templates.init_templates import (
    INDEX_TEMPLATE,
    PROJECT_MAP_TEMPLATE,
    WS_TEMPLATE,
)


def collect_metadata(
    target_dir: Path, non_interactive: bool
) -> tuple[str, str, str]:
    """Collect project metadata from user.

    Args:
        target_dir: Target directory for project
        non_interactive: Use defaults without prompting

    Returns:
        Tuple of (project_name, description, author)
    """
    import click

    project_name = target_dir.name
    description = "SDP project"
    author = "Your Name"

    if non_interactive:
        return project_name, description, author

    # Interactive prompts
    click.echo(click.style("Step 1: Project Metadata", fg="cyan", bold=True))

    project_name = click.prompt(
        "Project name",
        default=project_name,
        type=str,
    )

    description = click.prompt(
        "Description",
        default=description,
        type=str,
    )

    author = click.prompt(
        "Author",
        default=author,
        type=str,
    )

    return project_name, description, author


def create_structure(
    target_dir: Path, project_name: str, force: bool
) -> tuple[list[str], list[str]]:
    """Create directory structure.

    Args:
        target_dir: Target directory
        project_name: Name of project
        force: Overwrite existing files

    Returns:
        Tuple of (created_files, skipped_files)
    """
    current_date = datetime.now().strftime("%Y-%m-%d")

    # Define paths
    docs_dir = target_dir / "docs"
    workstreams_dir = docs_dir / "workstreams"
    backlog_dir = workstreams_dir / "backlog"
    project_map_file = docs_dir / "PROJECT_MAP.md"
    index_file = workstreams_dir / "INDEX.md"
    template_file = workstreams_dir / "TEMPLATE.md"
    sdp_local_dir = target_dir / "sdp.local"

    created_files = []
    skipped_files = []

    # Create directories
    for directory in [docs_dir, workstreams_dir, backlog_dir, sdp_local_dir]:
        if not directory.exists():
            directory.mkdir(parents=True)
            created_files.append(str(directory) + "/")

    # Create PROJECT_MAP.md
    if project_map_file.exists() and not force:
        skipped_files.append(str(project_map_file))
    else:
        content = PROJECT_MAP_TEMPLATE.format(
            project_name=project_name,
            date=current_date,
        )
        project_map_file.write_text(content)
        created_files.append(str(project_map_file))

    # Create INDEX.md
    if index_file.exists() and not force:
        skipped_files.append(str(index_file))
    else:
        index_file.write_text(INDEX_TEMPLATE)
        created_files.append(str(index_file))

    # Create TEMPLATE.md
    if template_file.exists() and not force:
        skipped_files.append(str(template_file))
    else:
        template_file.write_text(WS_TEMPLATE)
        created_files.append(str(template_file))

    return created_files, skipped_files


def generate_quality_gate(target_dir: Path, deps: dict[str, bool]) -> Path | None:
    """Generate quality-gate.toml configuration.

    Args:
        target_dir: Target directory
        deps: Detected optional dependencies

    Returns:
        Path to created file or None
    """
    import click

    quality_gate_file = target_dir / "quality-gate.toml"

    if quality_gate_file.exists():
        click.echo("⊘ quality-gate.toml already exists, skipping")
        return None

    # Generate configuration
    config = _get_quality_gate_config(deps)
    quality_gate_file.write_text(config)

    click.echo(f"✓ Created {quality_gate_file}")
    return quality_gate_file


def _get_quality_gate_config(deps: dict[str, bool]) -> str:
    """Get quality-gate.toml configuration.

    Args:
        deps: Detected optional dependencies

    Returns:
        TOML configuration string
    """
    # Base configuration
    config = """# SDP Quality Gate Configuration
# Auto-generated by sdp init

[coverage]
enabled = true
minimum = 80
fail_under = 80
exclude_patterns = [
    "*/tests/*",
    "*/test_*.py",
]

[complexity]
enabled = true
max_cc = 10
max_average_cc = 5

[file_size]
enabled = true
max_lines = 200
max_imports = 20
max_functions = 15

[type_hints]
enabled = true
require_return_types = true
require_param_types = true

[error_handling]
enabled = true
forbid_bare_except = true
forbid_pass_with_except = true

[architecture]
enabled = true
forbid_violations = [
    "domain -> application",
    "domain -> infrastructure",
    "domain -> presentation",
    "application -> infrastructure",
    "application -> presentation",
]
"""

    # Add Beads-specific configuration if detected
    if deps.get("Beads CLI"):
        config += """
# Beads integration
[testing]
enabled = true
require_test_for_new_code = true
"""

    return config


def create_env_template(target_dir: Path, deps: dict[str, bool]) -> Path | None:
    """Create .env.template file.

    Args:
        target_dir: Target directory
        deps: Detected optional dependencies

    Returns:
        Path to created file or None
    """
    import click

    env_template = target_dir / ".env.template"

    if env_template.exists():
        click.echo("⊘ .env.template already exists, skipping")
        return None

    # Generate template
    template = "# Environment Variables\n"
    template += "# Copy this file to .env and fill in values\n\n"

    # Add Telegram configuration if detected
    if deps.get("Telegram"):
        template += "# Telegram Notifications\n"
        template += "TELEGRAM_BOT_TOKEN=your_bot_token_here\n"
        template += "TELEGRAM_CHAT_ID=your_chat_id_here\n"
        template += "\n"

    # Add GitHub configuration if detected
    if deps.get("GitHub CLI (gh)"):
        template += "# GitHub Integration\n"
        template += "GITHUB_TOKEN=ghp_xxxxxxxxxxxxxxxxxxxx\n"
        template += "GITHUB_REPO=owner/repo\n"
        template += "\n"

    # Add Beads configuration if detected
    if deps.get("Beads CLI"):
        template += "# Beads Task Tracking\n"
        template += "BEADS_API_URL=http://localhost:8000\n"
        template += "\n"

    env_template.write_text(template)
    click.echo(f"✓ Created {env_template}")
    return env_template
